### ISSUE TITLE
Breaks printf demo

### ISSUE THREAD

**Issue by maxgerhardt** [CTXz/STM8-DCE#2]
The demo code https://github.com/platformio/platform-ststm8/tree/develop/examples/spl-uart-simple-printf/src

uses `putchar`,  but running it through the dead code eliminator, it optimizes that function away completely, resulting in a final link error of 

```
?ASlink-Warning-Undefined Global '_putchar' referenced by module 'puts'
```

verbose output:

https://pastebin.com/1i98UMys

**Comment by CTXz** [comment]
This issue should now be resolved with [this commit](https://github.com/CTXz/STM8-DCE/commit/d062c608d15a82608d7e7018cef83f8ebebeef54).

The standard library is linked and not assembled with the source files, making it inaccessible to the stm8dce tool. Consequently, stm8dce cannot detect that the standard library requires specific functions.

To address this, I've added a hardcoded list of functions that SDCC may require and that should never be optimized away. Currently, the list includes only `_getchar()` and `_putchar()`. 

From my review of the SDCC manual, these are the only functions that the standard library necessitates the user to implement. If anyone is aware of are additional functions that need to be included, please let me know!

Please confirm if the commit fixes your issue.

**Comment by maxgerhardt** [comment]
With `_getchar()` and `_putchar()` always being on the exclude list, could this have the side effect where a firmware deos implement those functions, but never ever calls `printf()` that would actually use these functions, and thus e.g. `printf()` bloats up the firmware extremely although it could be removed?

Would a better approach be to also feed a dynamically disassembled version of SDCC's standard library into the dead code optimizer so that it gets the whole picture?

**Comment by CTXz** [comment]
~Unfortunately, including the standard library always causes `print()` to bloat the firmware, regardless if `_getchar()` and `_putchar()` are even defined. This exposes two major issues:~

~1. Linked libraries are not optimized, always bloating up the firmware.~
2. stm8dce currently cannot determine if a library expects a function to be defined in the project source code.

For the standard library, point 2 has been addressed with the recent commit mentioned above. However, this does not solve this issue with other libraries. A potential fix could be to cross-reference the symbol tables for libraries and check if any function symbols in the library also exist in the project code.

~An even better solution, as you already suggested, would be to disassemble the library. In fact, an even better approach would be to disassemble the complete ELF file. If we could build a full non-optimized ELF, then disassemble, optimize, and reassemble it, it'd easily fix both problems. I'm just not aware of any tools that can do this for STM8. `stm8-objdump` can produce a disassembly, but to my knowledge, that cannot be reassembled?~

**Comment by CTXz** [comment]
Correction to my last post:

Turns out I totally misunderstood how SDCC links libraries. It does not include the full library, but only the "modules" within the library that are relevant. So yes, you are absolutely correct, including `_getchar()` and `_putchar()` would bloat the firmware with `printf()`, and not including them wouldn't.

For the standard library specifically, a disassembly theoretically is not required since the source files for it [can be found in the source code of `sdcc`](https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/). However, for more general cases it'd be really cool if compiled libraries could be optimized as well. I'm currently looking into the [`.rel` Object Module Format](https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/sdas/doc/format.txt) to see what can be done.
